version: '3.1'

services:
  app1:
    image: springboot-docker
    hostname: app1
    container_name: app1
    ports:
      - 8081:8000
    environment:
      - TZ=Asia/Shanghai

  app2:
    image: springboot-docker
    hostname: app2
    container_name: app2
    ports:
      - 8082:8000
    environment:
      - TZ=Asia/Shanghai